# Generated by Django 3.2.12 on 2022-03-26 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billets_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_artist', models.CharField(max_length=50)),
                ('skill_artist', models.CharField(max_length=50)),
                ('pics_artist', models.ImageField(blank=True, upload_to='picsArtist')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=50)),
                ('name_contact', models.CharField(max_length=50)),
                ('mail_contact', models.CharField(max_length=50)),
                ('pub_date', models.DateField(verbose_name='Date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=50)),
                ('av_ticket', models.IntegerField(default=0)),
                ('begin_date', models.DateTimeField(verbose_name="Date de debut d'event")),
                ('end_date', models.DateTimeField(verbose_name="Date de fin d'event")),
                ('description_event', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_user', models.ImageField(blank=True, upload_to='avatar')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hall', models.CharField(max_length=50)),
                ('size_hall', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.events')),
                ('hall_category', models.ManyToManyField(blank=True, to='event.HallCategory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.material')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=50)),
                ('type_group', models.CharField(max_length=50)),
                ('pics_group', models.ImageField(blank=True, upload_to='picsArtist')),
                ('artist', models.ManyToManyField(to='event.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='group',
            field=models.ManyToManyField(blank=True, to='event.Groups'),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype'),
        ),
        migrations.AddField(
            model_name='events',
            name='users',
            field=models.ManyToManyField(blank=True, through='event.Achat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achat',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.events'),
        ),
        migrations.AddField(
            model_name='achat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
